const swaggerAutogen = require('swagger-autogen')()

// 초기 생성용 스웨거 파일인듯 여기에 초기셋팅을 입력해주자
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
        "name": "User",
        "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    }
}

const outputFile = './swagger_output.json' // swagger-autogen이 실행 후 생성될 파일 위치와 이름 
 const endpointsFiles = ['./middlewares/posts.js', './middlewares/index.js', './middlewares/comment.js',] // 읽어올 Router가 정의되어 있는 js파일들
  //아래 코드에 .then() 이후를 삭제한다. 
  swaggerAutogen(outputFile, endpointsFiles, doc);